services:
  - type: web
    name: civ6-remote-controller
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PUBLIC_BASE_URL
        sync: false
